const { contextBridge, ipcRenderer } = require('electron');
ipcRenderer.on('native-capture-port',(event,message)=>window.postMessage({type:'showcase-capture-port',...message},'*',event.ports));
contextBridge.exposeInMainWorld('recorder', {
  updateState:()=>ipcRenderer.invoke('update-state'),
  checkForUpdates:()=>ipcRenderer.invoke('update-check'),
  installUpdate:()=>ipcRenderer.invoke('update-install'),
  updateActivity:value=>ipcRenderer.send('update-activity',value),
  onUpdateState:callback=>{const listener=(_,state)=>callback(state);ipcRenderer.on('update-state',listener);return()=>ipcRenderer.removeListener('update-state',listener);},
  openPrivacySettings: kind => ipcRenderer.invoke('open-privacy-settings',kind),
  logDiagnostics: (level, text) => ipcRenderer.send('diagnostics-log', level, String(text)),
  openLogs: () => ipcRenderer.invoke('open-logs'),
  getSettings: () => ipcRenderer.invoke('settings-get'),
  setSettings: patch => ipcRenderer.invoke('settings-set', patch),
  takeScreenshot: () => ipcRenderer.send('screenshot-take'),
  onScreenshot: callback => { const listener = (_, event) => callback(event); ipcRenderer.on('screenshot-event', listener); ipcRenderer.send('screenshot-mounted'); return () => ipcRenderer.removeListener('screenshot-event', listener); },
  screenshotDone: (rect, viewport) => ipcRenderer.invoke('screenshot-done', rect, viewport),
  screenshotCrop: rect => ipcRenderer.invoke('screenshot-crop', rect),
  screenshotCopy: () => ipcRenderer.invoke('screenshot-copy'),
  screenshotSave: () => ipcRenderer.invoke('screenshot-save'),
  screenshotCancel: () => ipcRenderer.send('screenshot-cancel'),
  saveProject: data => ipcRenderer.invoke('project-save',data),
  listProjects: () => ipcRenderer.invoke('project-list'),
  openProject: id => ipcRenderer.invoke('project-open',id),
  renameProject: (id,name) => ipcRenderer.invoke('project-rename',id,name),
  deleteProject: id => ipcRenderer.invoke('project-delete',id),
  saveProjectEdits: (id,edits) => ipcRenderer.invoke('project-save-edits',id,edits),
  moveProject: (id,folderId) => ipcRenderer.invoke('project-move',id,folderId),
  listFolders: () => ipcRenderer.invoke('folder-list'),
  createFolder: name => ipcRenderer.invoke('folder-create',name),
  renameFolder: (id,name) => ipcRenderer.invoke('folder-rename',id,name),
  deleteFolder: id => ipcRenderer.invoke('folder-delete',id),
  frameTimes: bytes => ipcRenderer.invoke('frame-times', bytes),
  editorExportStart: options => ipcRenderer.invoke('editor-export-start',options),
  editorExportFrame: bytes => ipcRenderer.invoke('editor-export-frame',bytes),
  editorExportFinish: () => ipcRenderer.invoke('editor-export-finish'),
  editorExportDispose: () => ipcRenderer.invoke('editor-export-dispose'),
  setEditorWindow: enabled => ipcRenderer.invoke('window-editor', enabled),
  minimizeWindow: () => ipcRenderer.invoke('window-minimize'),
  closeWindow: () => ipcRenderer.invoke('window-close'),
  sources: () => ipcRenderer.invoke('sources'),
  select: id => ipcRenderer.invoke('select', id),
  areaSource: () => ipcRenderer.invoke('area-source'),
  active: value => ipcRenderer.invoke('active', value),
  trackClicks: sourceId => ipcRenderer.invoke('track-clicks', sourceId),
  nativeCaptureStart: (sourceId, fps, token, selection, record) => ipcRenderer.invoke('native-capture-start', sourceId, fps, token, selection, record),
  nativeCaptureCommand: (id, type) => ipcRenderer.invoke('native-capture-command', id, type),
  nativeCaptureFinish: (id, audio) => ipcRenderer.invoke('native-capture-finish', id, audio),
  nativeCaptureStop: id => ipcRenderer.invoke('native-capture-stop',id),
  onRecordingPointer: callback => { const listener = (_, point) => callback(point); ipcRenderer.on('recording-pointer', listener); return () => ipcRenderer.removeListener('recording-pointer', listener); },
  onRecordingActivity: callback => { const listener = (_, activity) => callback(activity); ipcRenderer.on('recording-activity', listener); return () => ipcRenderer.removeListener('recording-activity', listener); },
  onRecordingClick: callback => { const listener = (_, point) => callback(point); ipcRenderer.on('recording-click', listener); return () => ipcRenderer.removeListener('recording-click', listener); },
  setInteractive: value => ipcRenderer.send('interactive', value),
  save: bytes => ipcRenderer.invoke('save', bytes),
  export: (bytes, options) => ipcRenderer.invoke('export', bytes, options),
  chooseExportFolder: current => ipcRenderer.invoke('export-choose-folder', current),
  cancelExport: () =>ipcRenderer.invoke('export-cancel'),
  onExportProgress: callback => { const listener = (_, percent) => callback(percent); ipcRenderer.on('export-progress', listener); return () => ipcRenderer.removeListener('export-progress', listener); },
  onStop: callback => { const listener = () => callback(); ipcRenderer.on('stop', listener); return () => ipcRenderer.removeListener('stop', listener); }
});
